language: python


python:
  - "2.7"
  - "3.5"

install:
  - pip install numpy
  - pip install scipy
  - pip install -r requirements.txt
  - pip install .
  - pip install coverage coveralls

script:
  - pytest
  - nosetests -s --with-coverage --cover-package=seglearn seglearn/tests

after_success:
  - coveralls || echo "Coveralls upload failed"
