language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"

install:
  - pip install numpy
  - pip install scipy
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest pytest-cov coverage coveralls
  - pip install travis-sphinx
  - pip install sphinx_rtd_theme sphinx_gallery numpy doc

script:
  - pytest --cov seglearn

after_success:
  - coveralls
