language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install numpy
  - pip install scipy
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest pytest-cov coverage coveralls

script:
  - pytest --cov seglearn

after_success:
  - coveralls
