language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=seglearn

matrix:
  include:
    # This environment tests the using anaconda
    # Ubuntu 14.04 environment
    - env: DISTRIB="ubuntu"
    # Latest release
    - env: DISTRIB="conda" PYTHON_VERSION="2.7"
           NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1" SKLEARN_VERSION="0.19.0"
    - env: DISTRIB="conda" PYTHON_VERSION="3.5"
           NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1" SKLEARN_VERSION="0.19.0"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6"
           NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1" SKLEARN_VERSION="0.19.0"
    - env: DISTRIB="conda" PYTHON_VERSION="3.6"
           NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1" SKLEARN_VERSION="master"
  allow_failures:
    - env: DISTRIB="conda" PYTHON_VERSION="3.6"
           NUMPY_VERSION="1.13.1" SCIPY_VERSION="0.19.1" SKLEARN_VERSION="master"


install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh
