version: 2

jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
      - checkout
      - run:
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            chmod +x miniconda.sh && ./miniconda.sh -b -p ~/miniconda
            export PATH="~/miniconda/bin:$PATH"
            conda update --yes --quiet conda
            conda create -n testenv --yes --quiet python=3
            source activate testenv
            conda install --yes pip numpy scipy scikit-learn matplotlib sphinx sphinx_rtd_theme numpydoc pillow keras pandas
            pip install sphinx-gallery
            pip install .
            cd doc
            make html
      - store_artifacts:
          path: doc/_build/html
          destination: doc
      - store_artifacts:
          path: ~/log.txt
      - persist_to_workspace:
          root: doc/_build/html
          paths: .
      - attach_workspace:
          at: doc/_build/html
      - run: ls -ltrh doc/_build/html
      - deploy:
          command: |
            git config --global user.email "david.mo.burns@gmail.com"
            git config --global user.name "dmbee"
            cd $HOME
            rm -rf tmp
            mkdir tmp
            cp -R $HOME/seglearn/doc/_build/html/* ./tmp/
            git clone https://github.com/dmbee/seglearn.git out
            cd out
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .
            cp -R $HOME/tmp/* ./
            touch .nojekyll
            git add -A
            git commit -m "Automated deployment to GitHub Pages"
            git push origin gh-pages
